package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"Gqlgen/controllers"
	"Gqlgen/db"
	"Gqlgen/graph/model"
	"context"
	"fmt"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateJoke(ctx context.Context, input model.JokeInput) (*model.JokeResp, error) {
	joke, err := controllers.CreateNewJoke(input)
	if err != nil {
		return nil, err
	}
	return joke, nil
}

// Migration is the resolver for the migration field.
func (r *mutationResolver) Migration(ctx context.Context) (*model.Generated, error) {
	var migResp model.Generated

	migResp.Message = "Table has been generated!"
	joke := `CREATE TABLE IF NOT EXISTS MyJoke(
	id serial PRIMARY KEY,
	joke VARCHAR(50) NOT NULL
	);`
	fmt.Println(joke)
	_, err := db.DbConn.Exec(joke)
	fmt.Println("i am in dbconn execution process")
	if err != nil {
		//fmt.Errorf(err.Error())
		return nil, err
	}
	fmt.Println("i passed the execution process")
	return &migResp, nil
}

// Joke is the resolver for the joke field.
func (r *queryResolver) Joke(ctx context.Context, id string) (*model.JokeResp, error) {
	joke, err := controllers.GetAJoke(id)
	if err != nil {
		return nil, err
	}
	return joke, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Jokes(ctx context.Context) ([]*model.JokeResp, error) {
	jokes, err := controllers.GetAllJoke()
	if err != nil {
		return nil, err
	}
	return jokes, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
