// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Generated struct {
	Message string `json:"message"`
}

type JokeInput struct {
	Text string `json:"text"`
}

type JokeResp struct {
	ID   *string `json:"id,omitempty"`
	Text *string `json:"text,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
